# Generated by Django 3.0.6 on 2020-06-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
